spring:
  main:
    banner-mode: off
    web-application-type: none
  datasource:
    url: jdbc:postgresql://localhost:5442/ledger_db
    username: rxman
    password: secretpass
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update   # for learning only
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    open-in-view: false