spring:
  datasource:
    url: jdbc:postgresql://localhost:5442/ledger_db
    username: rxman
    password: secretpass
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update   # for learning only
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    open-in-view: false

  main:
    web-application-type: none  # IMPORTANT (no web server)

logging:
  # Turn off all console logging
  level:
    root: OFF
  # Disable default console appender
  console:
    enabled: false
  file:
    # Optional: write logs to file
    name: logs/ledger-mcp.log
